pre-commit:
  parallel: true
  commands:
    prettier:
      run: pnpm prettier

    lint:
      run: |
        CHANGED=$(git diff --cached --name-only \
          | grep -E '^(apps|packages|tooling)/' \
          | cut -d/ -f1,2 \
          | sort -u \
          | sed 's#^#./#' \
          | tr '\n' ',')

        [ -z "$CHANGED" ] || turbo run lint --filter="$CHANGED"

    typecheck:
      run: |
        CHANGED=$(git diff --cached --name-only \
          | grep -E '^(apps|packages|tooling)/' \
          | cut -d/ -f1,2 \
          | sort -u \
          | sed 's#^#./#' \
          | tr '\n' ',')

        [ -z "$CHANGED" ] || turbo run typecheck --filter="$CHANGED"

    format:
      run: pnpm format
      stage_fixed: true

commit-msg:
  commands:
    commitlint:
      run: pnpm commitlint --edit {1}
