pre-commit:
  parallel: true
  commands:
    prettier:
      run: pnpm prettier

    lint:
      run: |
        CHANGED=$(git diff --cached --name-only \
          | grep -E '^(apps|packages|tooling)/' \
          | cut -d/ -f1,2 \
          | sort -u)

        if [ -n "$CHANGED" ]; then
          FILTERS=$(echo "$CHANGED" | while read dir; do
            if [ -f "$dir/package.json" ]; then
              NAME=$(grep -m1 '"name"' "$dir/package.json" | sed 's/.*"name": *"\([^"]*\)".*/\1/')
              echo "--filter=$NAME"
            fi
          done | tr '\n' ' ')
          turbo run lint $FILTERS
        fi

    typecheck:
      run: |
        CHANGED=$(git diff --cached --name-only \
          | grep -E '^(apps|packages|tooling)/' \
          | cut -d/ -f1,2 \
          | sort -u)

        if [ -n "$CHANGED" ]; then
          FILTERS=$(echo "$CHANGED" | while read dir; do
            if [ -f "$dir/package.json" ]; then
              NAME=$(grep -m1 '"name"' "$dir/package.json" | sed 's/.*"name": *"\([^"]*\)".*/\1/')
              echo "--filter=$NAME"
            fi
          done | tr '\n' ' ')
          turbo run typecheck $FILTERS
        fi

    format:
      run: pnpm format
      stage_fixed: true

commit-msg:
  run: pnpm commitlint --edit {1}
