packages:
  - "apps/*"
  - "packages/*"
  - "tooling/*"

catalog:
  typescript: 5.9.2

# 필요시 catalog key 커스텀
catalogs:
  react19.1:
    react: 19.1.0
    react-dom: 19.1.0
    "@types/react": ~19.1.0
    "@types/react-dom": ~19.1.0
