/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/members/terms': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 약관 동의
     * @description 소셜 로그인 직후 'PENDING_TERMS' 상태인 회원이 필수 약관에 동의하는 단계입니다. <br>
     *     성공 시 회원의 상태는 'PENDING_ONBOARDING'으로 변경되며, 이후 온보딩(크루 참여/생성)이 가능해집니다. <br>
     *     PENDING_TERMS 상태의 회원만 약관 동의 API를 호출할 수 있으므로 다른 상태일 경우 INVALID_MEMBER_STATUS 오류가 발생합니다.
     */
    post: operations['agreeToTerms'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/social-login/{provider}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 소셜 로그인
     * @description 인가 코드를 통해 소셜 로그인을 진행하고 JWT 토큰을 발급합니다.
     */
    post: operations['socialLogin'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/reissue': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 토큰 재발급
     * @description 쿠키에 저장된 Refresh Token을 사용하여 Access Token을 갱신합니다. (RTR 방식 적용)
     */
    post: operations['reissue'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 로그아웃
     * @description 현재 사용자의 세션을 종료하고 리프레시 토큰 쿠키를 제거합니다.
     */
    post: operations['logout'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    AgreeToTermsRequest: {
      /** @description 서비스 이용약관 동의 여부 (필수) */
      serviceTermsAgreed: boolean;
      /** @description 개인정보 처리방침 동의 여부 (필수) */
      privacyPolicyAgreed: boolean;
      /** @description 위치기반 서비스 이용약관 동의 여부 (필수) */
      locationServiceAgreed: boolean;
      /** @description 제3자 정보제공 동의 여부 (필수) */
      thirdPartyInfoAgreed: boolean;
      /** @description 마케팅 정보 수신 동의 여부 (선택) */
      marketingTermsAgreed: boolean;
    };
    CommonResponseVoid: {
      code?: string;
      message?: string;
      result?: Record<string, never>;
    };
    SocialLoginRequest: {
      /** @description 소셜 서비스로부터 발급받은 인가 코드 */
      authorizationCode: string;
      /** @description 애플 전용 ID Token */
      idToken?: string;
      /** @description 애플 최초 가입 시 제공되는 사용자 정보 (JSON String) */
      user?: string;
    };
    CommonResponseSocialLoginResponse: {
      code?: string;
      message?: string;
      result?: components['schemas']['SocialLoginResponse'];
    };
    SocialLoginResponse: {
      /** @description 액세스 토큰 */
      accessToken?: string;
      /**
       * Format: int64
       * @description 액세스 토큰 만료 시간 (초)
       */
      accessTokenExpiresIn?: number;
      /**
       * @description 회원 상태
       * @enum {string}
       */
      status?:
        | 'ACTIVE'
        | 'WITHDRAWN'
        | 'PENDING_TERMS'
        | 'PENDING_ONBOARDING'
        | 'WAITING_FOR_APPROVE';
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  agreeToTerms: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AgreeToTermsRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['CommonResponseVoid'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  socialLogin: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        provider: 'KAKAO' | 'APPLE';
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SocialLoginRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['CommonResponseSocialLoginResponse'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  reissue: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['CommonResponseSocialLoginResponse'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['CommonResponseVoid'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
}
