/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/addresses/{addressId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * 배송지 수정
     * @description 기존 배송지 정보를 수정합니다. <br><br>
     *
     *     **[참고 사항]** <br>
     *     * 본인의 배송지만 수정 가능합니다. (FORBIDDEN_ADDRESS_ACCESS)
     *     * 모든 필드는 필수 입력 항목입니다. (INVALID_ADDRESS_INPUT)
     *     * 해당 주소를 '기본 배송지'로 변경 시, 기존의 다른 기본 배송지는 해제됩니다.
     */
    put: operations['updateDeliveryAddress'];
    post?: never;
    /**
     * 배송지 삭제
     * @description 등록된 배송지를 삭제합니다. <br><br>
     *
     *     **[참고 사항]** <br>
     *     * 본인의 배송지만 삭제 가능합니다. (FORBIDDEN_ADDRESS_ACCESS)
     *     * 기본 배송지일 경우 삭제가 불가능합니다. (CANNOT_DELETE_DEFAULT_ADDRESS)
     */
    delete: operations['deleteDeliveryAddress'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/orders': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 주문 내역 목록 조회 (무한 스크롤)
     * @description 커서 기반 페이징을 사용하여 사용자의 전체 주문 내역을 최신순으로 조회합니다. <br><br>
     *
     *     **[참고 사항]** <br>
     *     * 무한 스크롤 방식: hasNext를 통해 다음 페이지 존재 여부를 확인하고, lastId를 다음 요청의 cursorId로 호출하면 됩니다.
     *     * 상품명, 브랜드명, 이미지 등은 구매 시점의 정보를 제공하므로 현재의 상품 정보와 다를 수 있습니다.
     */
    get: operations['getOrders'];
    put?: never;
    /**
     * 주문 생성 (결제)
     * @description 최종 결제 정보와 배송지를 입력받아 주문을 생성하고 상품 재고를 차감합니다. <br><br>
     *
     *     **[참고사항]** <br>
     *     * 주문 시점에 각 SKU의 재고가 즉시 차감됩니다.
     *     * 보유 포인트 잔액과 최소 사용 단위(1,000P)를 검증합니다. (INVALID_POINT_USAGE)
     *     * 결제 수단 (MVP): 현재 '무통장 입금(BANK_TRANSFER)'만 지원합니다. 그 외 수단은 에러를 반환합니다. (PAYMENT_METHOD_NOT_SUPPORTED)
     *     * 주문이 성공하면 선택한 장바구니 아이템들은 자동으로 삭제됩니다.
     */
    post: operations['createOrder'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/members/terms': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 약관 동의
     * @description 소셜 로그인 직후 '약관 동의 대기(PENDING_TERMS)' 상태인 회원이 필수 서비스 약관에 동의하는 단계입니다. <br><br>
     *
     *     **[제약 사항]** <br>
     *     * '약관 동의 대기(PENDING_TERMS)' 상태의 회원만 호출 가능합니다. (INVALID_MEMBER_STATUS)
     *     * 필수 약관 중 하나라도 누락될 경우 가입이 진행되지 않습니다. (REQUIRED_TERMS_NOT_AGREED)
     */
    post: operations['agreeToTerms'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/members/me/withdraw': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 회원 탈퇴
     * @description 서비스 이용을 중단하고 회원의 소셜 연동 해제 및 탈퇴 처리를 진행합니다. <br><br>
     */
    post: operations['withdraw'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/members/me/confirm-status': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 가입 승인/거절 결과 확인
     * @description 사용자가 가입 요청에 대한 승인 또는 거절 결과를 확인했음을 서버에 알립니다. <br><br>
     *
     *     **[참고 사항]** <br>
     *     * APPROVED_PENDING_CONFIRM 또는 REJECTED_PENDING_CONFIRM 상태인 회원만 호출 가능합니다. (INVALID_MEMBER_STATUS)
     *     * 가입 승인 완료 화면에서 '홈으로' 버튼 클릭 시 호출: 멤버 상태가 APPROVED_PENDING_CONFIRM -> ACTIVE로 변경됩니다.
     *     * 가입 거절 안내 화면에서 '처음으로' 버튼 클릭 시 호출: 멤버 상태가 REJECTED_PENDING_CONFIRM -> PENDING_ONBOARDING으로 변경됩니다.
     */
    post: operations['confirmMemberStatus'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/crews': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 크루 생성
     * @description 새로운 크루를 생성하고 고유한 초대 코드를 발급합니다. <br>
     *     성공 시 영문 대문자와 숫자로 조합된 6자리 초대 코드를 반환합니다. <br><br>
     *
     *     **[입력 데이터]** <br>
     *     * 카테고리(category): RUNNING
     *     * 활동 지역(region): SEOUL, GYEONGGI_INCHEON, CHUNGCHEONG_DAEJEON, JEOLLA_GWANGJU, GYEONGBUK_DAEGU, GYEONGNAM_BUSAN, GANGWON, JEJU <br><br>
     *
     *     **[제약 사항]** <br>
     *     * 크루 이름: 최대 15자 이내로 작성해야 합니다. (INVALID_INPUT_VALUE)
     *     * 온보딩 단계(PENDING_ONBOARDING) 또는 정회원(ACTIVE) 상태의 사용자만 요청 가능합니다. (INVALID_MEMBER_STATUS)
     */
    post: operations['createCrew'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/crews/{crewId}/join-requests/{targetMemberId}/reject': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 가입 요청 거절
     * @description 크루 리더가 대기 중인 가입 요청을 거절합니다. <br><br>
     *
     *     **[제약 사항]** <br>
     *     * 해당 크루의 **리더(LEADER)**만 이 API를 호출할 수 있습니다. (FORBIDDEN_ERROR)
     */
    post: operations['rejectJoinRequest'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/crews/{crewId}/join-requests/{targetMemberId}/approve': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 가입 요청 승인
     * @description 크루 리더가 대기 중인 가입 요청을 승인합니다. <br><br>
     *
     *     **[제약 사항]** <br>
     *     * 해당 크루의 리더(LEADER)만 API를 호출할 수 있습니다. (FORBIDDEN_ERROR)
     */
    post: operations['approveJoinRequest'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/crews/join': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 크루 가입 신청
     * @description 6자리 초대 코드를 입력하여 특정 크루에 가입 신청을 보냅니다. <br>
     *     크루 리더의 승인이 완료되기 전까지는 정회원(ACTIVE)으로 전환되지 않습니다. <br><br>
     *
     *     **[제약 사항]** <br>
     *     * 본인이 리더인 크루이거나 이미 멤버로 등록된 크루에는 재신청이 불가합니다. (ALREADY_JOINED_CREW)
     *     * 유효하지 않은 초대 코드를 입력할 경우 가입이 불가합니다. (CREW_NOT_FOUND)
     */
    post: operations['joinCrew'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/carts/items': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 장바구니 항목 추가 및 수량 변경
     * @description 상품의 특정 옵션(SKU)을 장바구니에 담거나 기존 항목의 수량을 추가합니다. <br><br>
     *
     *     **[참고 사항]** <br>
     *     * 장바구니에 해당 SKU가 없는 경우 새로운 항목으로 등록됩니다.
     *     * 이미 동일한 SKU가 장바구니에 있는 경우, 기존 수량에 요청한 수량만큼 더해집니다.
     *     * 담으려는 총 수량이 상품의 실제 재고 수량을 초과할 경우 에러가 발생합니다. (OUT_OF_STOCK)
     *     * 수량은 최소 1개 이상이어야 합니다. (INVALID_QUANTITY)
     */
    post: operations['addCartItem'];
    /**
     * 장바구니 항목 삭제
     * @description 선택한 장바구니 항목들을 삭제합니다. <br><br>
     *
     *     **[동작 방식]** <br>
     *     * 단건 삭제: 리스트에 하나의 ID만 담아 요청합니다. (예: {"cartItemIds": [1]})
     *     * 다건 삭제: 삭제할 모든 ID를 리스트에 담아 요청합니다. (예: {"cartItemIds": [1, 2, 3]})
     *
     *     **[참고 사항]** <br>
     *     * 로그인한 사용자의 장바구니 항목만 삭제할 수 있습니다. 타인의 ID를 포함하더라도 해당 항목은 무시되고 본인의 것만 삭제됩니다.
     *     * 멱등성 보장을 위해 이미 삭제된 ID나 존재하지 않는 ID를 요청에 포함하더라도 에러를 발생시키지 않고 성공 처리합니다.
     */
    delete: operations['deleteItems'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/social-login/{provider}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 소셜 로그인 (애플 제외)
     * @description 카카오 등 소셜 플랫폼의 인가 코드를 통해 로그인을 진행하고 JWT 토큰과 회원의 현재 상태, 최근 가입한 크루 ID를 반환합니다. <br><br>
     *
     *     **[참고 사항]** <br>
     *     * 보안을 위해 리프레시 토큰은 HttpOnly 쿠키에 저장되어 발급됩니다.
     *     * 응답으로 받은 **status** 값에 따라 앱의 초기 진입 화면(약관 동의, 온보딩, 메인 등)을 결정해야 합니다. <br>
     */
    post: operations['socialLogin'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/social-login/apple': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 애플 소셜 로그인 (백엔드 전용)
     * @description 애플 서버로부터 직접 리다이렉트되는 콜백 엔드포인트입니다. 클라이언트가 아닌 서버 간 통신을 통해 로그인을 처리합니다. <br><br>
     */
    post: operations['appleLogin'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/reissue': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 토큰 재발급
     * @description 쿠키에 저장된 리프레시 토큰을 사용하여 액세스 토큰을 갱신합니다. <br><br>
     *
     *     **[RTR(Refresh Token Rotation) 방식 적용]** <br>
     *     * 토큰 재발급 시 기존 리프레시 토큰은 폐기되고 새로운 리프레시 토큰이 쿠키에 다시 저장됩니다. <br>
     *     * 만약 이미 사용된 리프레시 토큰이 다시 제출될 경우, 보안 위협으로 간주하여 쿠키 삭제 및 로그아웃됩니다. (TOKEN_REUSE_DETECTED)
     */
    post: operations['reissue'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 로그아웃
     * @description 현재 사용자의 세션을 종료하고 리프레시 토큰 쿠키를 제거합니다.
     */
    post: operations['logout'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/apple/notification': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 애플 서버 알림 수신 (S2S)
     * @description Apple 서버가 사용자 상태 변경 알림(계정 연동 해제 등)을 보낼 때 이를 수신하여 서버 데이터를 동기화합니다. <br><br>
     *
     *     **[수신 케이스]** <br>
     *     * CONSENT_REVOKED: 사용자가 Apple 설정에서 앱 연동을 해제한 경우 탈퇴 처리를 진행합니다. <br>
     *     * ACCOUNT_DELETE: Apple 계정이 삭제된 경우 탈퇴 처리를 진행합니다.
     *     * EMAIL_ENABLED: 사용자가 Apple 설정에서 이메일 공유를 활성화한 경우(숨기기 해제) 해당 플래그를 Y로 설정합니다.
     *     * EMAIL_DISABLED: 사용자가 Apple 설정에서 이메일 공유를 비활성화한 경우(숨기기 설정) 해당 플래그를 N으로 설정합니다.
     */
    post: operations['receiveAppleNotification'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/addresses': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 배송지 목록 조회
     * @description 사용자의 모든 배송지 목록을 조회합니다. <br><br>
     *
     *     **[정렬 기준]** <br>
     *     1. 기본 배송지가 가장 상단에 노출됩니다. <br>
     *     2. 그 외 주소는 최신 등록순으로 정렬됩니다.
     */
    get: operations['getDeliveryAddresses'];
    put?: never;
    /**
     * 배송지 등록
     * @description 신규 배송지 정보를 등록합니다. <br><br>
     *
     *     **[참고 사항]** <br>
     *     * 수령인, 연락처, 우편번호, 기본 주소, 상세 주소는 모두 필수 입력 항목입니다. (INVALID_ADDRESS_INPUT)
     *     * 사용자의 첫 번째 배송지 등록인 경우, 요청값과 관계없이 자동으로 '기본 배송지'로 설정됩니다.
     *     * 새 주소를 기본 배송지(isDefault: true)로 등록할 경우, 기존에 설정된 기본 배송지는 자동으로 일반 배송지로 변경됩니다.
     */
    post: operations['registerDeliveryAddress'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/orders/{orderNumber}/cancel': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * 주문 취소
     * @description 주문 상태가 결제 대기(PENDING) 혹은 결제 완료(PAID)인 경우에만 취소가 가능합니다. <br><br>
     *
     *     **[내부 로직]** <br>
     *     1. 주문 상태를 CANCELLED(주문 취소)로 변경합니다.
     *     2. 주문했던 상품의 재고를 주문 수량만큼 다시 증가시킵니다.
     *     3. 사용했던 포인트를 사용자 계정으로 전액 환불합니다.
     */
    patch: operations['cancelOrder'];
    trace?: never;
  };
  '/api/v1/products': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 상품 목록 조회 (무한 스크롤)
     * @description 커서 기반 페이징을 사용하여 전체 상품 목록을 최신순으로 조회합니다. <br><br>
     *
     *     **[참고 사항]** <br>
     *     * 무한 스크롤 방식: hasNext를 통해 다음 페이지 존재 여부를 확인하고, lastId를 다음 요청의 cursorId로 호출하면 됩니다.
     */
    get: operations['getProducts'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/products/{productId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 상품 상세 정보 조회
     * @description 상품의 상세 정보, 이미지 리스트, 옵션 그룹 및 재고 정보를 조회합니다. <br><br>
     *
     *     **[데이터 구조]** <br>
     *     * expectedShippingDate: 상품의 배송 출고 소요 시간을 기준으로 자동 계산된 예상 배송 시작일입니다.
     *     * slideImageUrls: 상품 상단 배너에 노출할 이미지 리스트입니다.
     *     * detailImageUrls: 상품 하단 상세 설명 영역에 노출할 이미지 리스트입니다.
     *     * skus: 선택 가능한 옵션 조합(SKU) 리스트입니다. 각 SKU는 optionValueIds 리스트를 통해 어떤 옵션값들의 조합인지 나타냅니다.
     *
     *     **[참고 사항]** <br>
     *     * 옵션 관련 데이터들은 DB에 저장된 노출 순서를 기준으로 정렬되어 있습니다.
     */
    get: operations['getProduct'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/orders/{orderNumber}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 주문 상세 조회
     * @description 특정 주문 번호를 기반으로 주문의 상세 내역을 조회합니다. <br><br>
     *
     *     **[참고 사항]** <br>
     *     * 요청한 사용자가 해당 주문의 소유자인지 확인하며, 타인의 주문 조회 시 에러를 반환합니다. (FORBIDDEN_ERROR)
     *     * 구매 당시의 상품명, 브랜드명, 옵션 정보, 이미지 및 수량이 반영된 가격 정보를 포함하는 '스냅샷' 정보를 제공합니다.
     *     * API 호출 시에는 #이 없는 형태(예: AZ2602104434)를 사용합니다. 단, API 응답 시에는 UI 가독성을 위해 주문번호에 #을 접두어로 붙여 반환합니다.
     */
    get: operations['getOrderDetail'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/orders/checkout/direct': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 주문서 조회(바로 구매)
     * @description 상품 상세에서 선택한 상품을 바탕으로 주문서(결제 상세 페이지)에 필요한 정보를 조회합니다. <br><br>
     *
     *     **[참고 사항]** <br>
     *     * 파라미터 deliveryAddressId가 있을 경우, deliveryAddressId로 배송지 정보를 조회합니다.
     *     * 파라미터 deliveryAddressId가 없을 경우, 사용자의 기본 배송지 정보를 조회합니다. (없을 경우 null 반환)
     *     * 브랜드별로 가장 높은 배송비를 한 번씩만 합산하여 계산합니다.
     *     * 보유 포인트와 함께 사용 가능한 최소 단위(1,000P), 입력 단위(100P) 정보를 제공합니다.
     *     * 현재 사용 가능한 결제 수단 목록과 활성화 여부를 제공합니다. (네이버페이는 현재 비활성화 상태)
     *     * '아지트 멤버십 할인'은 각 상품의 (정가 - 판매가) 총합으로 계산됩니다.
     *     * 포인트 '모두 사용' 클릭 시 응답의 availablePoints 값을 활용하여 100P 단위로 가공하시면 됩니다.
     */
    get: operations['getCheckoutInfoDirect'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/orders/checkout/cart': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 주문서 조회(장바구니)
     * @description 장바구니에서 선택한 상품들을 바탕으로 주문서(결제 상세 페이지)에 필요한 정보를 조회합니다. <br><br>
     *
     *     **[참고 사항]** <br>
     *     * 파라미터 deliveryAddressId가 있을 경우, deliveryAddressId로 배송지 정보를 조회합니다.
     *     * 파라미터 deliveryAddressId가 없을 경우, 사용자의 기본 배송지 정보를 조회합니다. (없을 경우 null 반환)
     *     * 브랜드별로 가장 높은 배송비를 한 번씩만 합산하여 계산합니다.
     *     * 보유 포인트와 함께 사용 가능한 최소 단위(1,000P), 입력 단위(100P) 정보를 제공합니다.
     *     * 현재 사용 가능한 결제 수단 목록과 활성화 여부를 제공합니다.
     *     * '아지트 멤버십 할인'은 각 상품의 (정가 - 판매가) 총합으로 계산됩니다.
     *     * 포인트 '모두 사용' 클릭 시 응답의 availablePoints 값을 활용하여 100P 단위로 가공하시면 됩니다.
     */
    get: operations['getCheckoutInfoFromCart'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/members/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 내 정보 조회(마이페이지)
     * @description 로그인한 사용자의 기본 정보를 조회합니다. <br><br>
     *
     *     **[참고 사항]** <br>
     *     * 소속 크루가 없으면 null을 반환합니다.
     */
    get: operations['getMyInfo'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/crews/{crewId}/members': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 크루 멤버 목록 조회
     * @description 커서 기반 페이징을 사용하여 해당 크루에 가입되어 있는 모든 멤버의 목록을 조회합니다. <br><br>
     *
     *     **[참고 사항]** <br>
     *     * 해당 크루에 가입된 멤버(JOINED 상태)만 이 API를 호출할 수 있습니다. (NOT_A_CREW_MEMBER)
     *     * 리더가 목록 최상단으로 정렬되고, 그 외 멤버는 가입일이 최신인 순서대로 정렬됩니다.
     *     * 무한 스크롤 방식: hasNext를 통해 다음 페이지 존재 여부를 확인하고, lastId를 다음 요청의 cursorId로 호출하면 됩니다.
     */
    get: operations['getCrewMembers'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/crews/{crewId}/join-status': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 가입 요청 상태 조회
     * @description 특정 크루에 신청한 멤버(로그인한 사용자) 가입 요청이 어떤 상태인지 조회합니다. <br><br>
     *
     *     **[응답 상태값]** <br>
     *     * REQUESTED: 승인 대기 중
     *     * JOINED: 승인 완료
     *     * REJECTED: 가입 거절
     */
    get: operations['getCrewJoinStatus'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/crews/{crewId}/join-requests': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 가입 신청 목록 조회
     * @description 크루 리더가 현재 승인 대기 중(REQUESTED)인 유저들의 목록을 조회합니다.
     */
    get: operations['getJoinRequests'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/crews/invitation/{invitationCode}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 초대 코드로 크루 정보 조회
     * @description 입력한 6자리 초대 코드가 유효한지 확인하고, 해당 크루의 요약 정보를 반환합니다. <br>
     *     사용자가 가입 신청을 하기 전, 크루 정보를 미리 확인할 때 사용합니다. <br><br>
     *
     *     **[제약 사항]** <br>
     *     * 존재하지 않거나 잘못된 초대 코드일 경우 CREW_NOT_FOUND 오류가 발생합니다.
     */
    get: operations['getCrewByInvitation'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/carts': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 장바구니 목록 조회
     * @description 사용자의 장바구니에 담긴 상품 목록과 결제 요약 정보를 조회합니다. <br><br>
     *
     *     **[데이터 구조]** <br>
     *     * totalProductPrice: 장바구니에 담긴 모든 상품의 '정가 + 옵션가' 합계입니다.
     *     * membershipDiscount: 아지트 멤버십 할인 금액입니다.
     *     * shippingFee: 브랜드별로 가장 높은 배송비를 한 번씩만 합산한 금액입니다.
     *     * expectedShippingDate: 상품의 예상 출고 소요 시간을 기준으로 계산되며, 주말(토, 일)은 발송일에서 제외됩니다.
     */
    get: operations['getCarts'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/carts/count': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 장바구니 수량 조회
     * @description 장바구니 아이콘에 표시될 아이템 종류 수를 조회합니다. <br><br>
     *
     *     **[참고 사항]** <br>
     *     * 상품의 총 수량 합계가 아닌 장바구니에 담긴 '품목'의 개수를 반환합니다.
     */
    get: operations['getCartItemCount'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    UpdateDeliveryAddressRequest: {
      /** @description 수령인 */
      recipientName: string;
      /** @description 수령인 연락처 */
      phoneNumber: string;
      /** @description 우편번호 */
      zipcode: string;
      /** @description 기본 주소 */
      baseAddress: string;
      /** @description 상세 주소 */
      detailAddress: string;
      /** @description 기본 배송지 여부 */
      isDefault: boolean;
    };
    CommonResponseVoid: {
      code?: string;
      message?: string;
      result?: Record<string, never>;
    };
    CreateOrderRequest: {
      /** @description 주문할 장바구니 아이템 ID 리스트(장바구니 구매용) */
      cartItemIds?: number[];
      /**
       * Format: int64
       * @description sku ID(바로 구매용)
       */
      skuId?: number;
      /**
       * Format: int32
       * @description 구매할 상품 수량(바로 구매용)
       */
      quantity?: number;
      /** @description 수령인 이름 */
      recipientName: string;
      /** @description 수령인 연락처 */
      phoneNumber: string;
      /** @description 기본 주소 */
      baseAddress: string;
      /** @description 상세 주소 */
      detailAddress: string;
      /** @description 배송 요청사항 */
      shippingInstruction?: string;
      /**
       * Format: int64
       * @description 사용할 포인트
       */
      usedPoints?: number;
      /** @description 결제 수단 */
      paymentMethod: string;
    };
    /** @description 최종 결제 금액 요약 */
    CheckoutSummaryResponse: {
      /**
       * Format: int64
       * @description 총 상품금액 (할인 전 합계)
       */
      totalProductPrice?: number;
      /**
       * Format: int64
       * @description 아지트 멤버십 할인 금액
       */
      membershipDiscount?: number;
      /**
       * Format: int64
       * @description 포인트 할인 금액
       */
      pointDiscount?: number;
      /**
       * Format: int64
       * @description 배송비
       */
      shippingFee?: number;
      /**
       * Format: int64
       * @description 최종 결제 금액
       */
      totalPaymentPrice?: number;
    };
    CommonResponseCreateOrderResponse: {
      code?: string;
      message?: string;
      result?: components['schemas']['CreateOrderResponse'];
    };
    CreateOrderResponse: {
      /** @description 주문 번호 */
      orderNumber?: string;
      deliveryInfo?: components['schemas']['OrderDeliveryInfoResponse'];
      depositAccountInfo?: components['schemas']['DepositAccountInfoResponse'];
      summary?: components['schemas']['CheckoutSummaryResponse'];
    };
    /** @description 입금 계좌 정보 */
    DepositAccountInfoResponse: {
      /** @description 은행명 */
      bankName?: string;
      /** @description 계좌번호 */
      accountNumber?: string;
      /** @description 예금주 */
      accountHolder?: string;
    };
    /** @description 배송지 정보 */
    OrderDeliveryInfoResponse: {
      /** @description 수령인 이름 */
      recipientName?: string;
      /** @description 수령인 연락처 */
      phoneNumber?: string;
      /** @description 기본 주소 */
      baseAddress?: string;
      /** @description 상세 주소 */
      detailAddress?: string;
    };
    AgreeToTermsRequest: {
      /** @description 서비스 이용약관 동의 여부 (필수) */
      serviceTermsAgreed: boolean;
      /** @description 개인정보 처리방침 동의 여부 (필수) */
      privacyPolicyAgreed: boolean;
      /** @description 위치기반 서비스 이용약관 동의 여부 (필수) */
      locationServiceAgreed: boolean;
      /** @description 제3자 정보제공 동의 여부 (필수) */
      thirdPartyInfoAgreed: boolean;
      /** @description 마케팅 정보 수신 동의 여부 (선택) */
      marketingTermsAgreed: boolean;
      /** @description 알림 수신 동의 여부 (선택) */
      notificationTermsAgreed: boolean;
    };
    CreateCrewRequest: {
      /** @description 크루 이름 */
      name: string;
      /** @description 크루 카테고리 */
      category: string;
      /** @description 크루 활동 지역 */
      region: string;
    };
    CommonResponseCreateCrewResponse: {
      code?: string;
      message?: string;
      result?: components['schemas']['CreateCrewResponse'];
    };
    CreateCrewResponse: {
      /** @description 초대코드 */
      invitationCode?: string;
    };
    JoinCrewRequest: {
      /** @description 초대코드 */
      invitationCode?: string;
    };
    AddToCartRequest: {
      /**
       * Format: int64
       * @description 상품 ID
       */
      productId: number;
      /**
       * Format: int64
       * @description 상품 옵션 조합(SKU) ID
       */
      productSkuId: number;
      /**
       * Format: int32
       * @description 담을 수량
       */
      quantity?: number;
    };
    SocialLoginRequest: {
      /** @description 소셜 서비스로부터 발급받은 인가 코드 */
      authorizationCode: string;
    };
    CommonResponseSocialLoginResponse: {
      code?: string;
      message?: string;
      result?: components['schemas']['SocialLoginResponse'];
    };
    SocialLoginResponse: {
      /** @description 액세스 토큰 */
      accessToken?: string;
      /**
       * Format: int64
       * @description 액세스 토큰 만료 시간 (초)
       */
      accessTokenExpiresIn?: number;
      /**
       * @description 회원 상태
       * @enum {string}
       */
      status?:
        | 'ACTIVE'
        | 'WITHDRAWN'
        | 'PENDING_TERMS'
        | 'PENDING_ONBOARDING'
        | 'WAITING_FOR_APPROVE'
        | 'APPROVED_PENDING_CONFIRM'
        | 'REJECTED_PENDING_CONFIRM';
      /**
       * Format: int64
       * @description 가입한 크루 ID (없을 경우 null)
       */
      crewId?: number;
    };
    AppleNotificationRequest: {
      /** @description Apple에서 전달한 페이로드 */
      payload: string;
    };
    RegisterDeliveryAddressRequest: {
      /** @description 수령인 */
      recipientName: string;
      /** @description 수령인 연락처 */
      phoneNumber: string;
      /** @description 우편번호 */
      zipcode: string;
      /** @description 기본 주소 */
      baseAddress: string;
      /** @description 상세 주소 */
      detailAddress: string;
      /** @description 기본 배송지 여부 */
      isDefault: boolean;
    };
    CursorPageQuery: {
      /** Format: int64 */
      cursorId?: number;
      /** Format: int32 */
      size?: number;
    };
    CommonResponseSliceResponseProductListResponse: {
      code?: string;
      message?: string;
      result?: components['schemas']['SliceResponseProductListResponse'];
    };
    /** @description 데이터 내용 */
    ProductListResponse: {
      /**
       * Format: int64
       * @description 상품 ID
       */
      id?: number;
      /** @description 브랜드명 */
      brandName?: string;
      /** @description 상품명 */
      productName?: string;
      /**
       * Format: int64
       * @description 정가
       */
      basePrice?: number;
      /**
       * Format: int32
       * @description 할인율
       */
      discountRate?: number;
      /**
       * Format: int64
       * @description 할인된 가격
       */
      salePrice?: number;
      /** @description 썸네일 이미지 url */
      thumbnailImageUrl?: string;
    };
    SliceResponseProductListResponse: {
      /** @description 데이터 내용 */
      content?: components['schemas']['ProductListResponse'][];
      /** @description 남은 페이지가 있는지 여부 (false면 마지막 페이지) */
      hasNext?: boolean;
      /**
       * Format: int64
       * @description 마지막 데이터의 ID, 다음 페이지 호출 시 해당 id를 cursorId에 넣어서 호출
       */
      lastId?: number;
    };
    CommonResponseProductDetailResponse: {
      code?: string;
      message?: string;
      result?: components['schemas']['ProductDetailResponse'];
    };
    /** @description 옵션 그룹 목록 */
    OptionGroupResponse: {
      /**
       * Format: int64
       * @description 옵션 그룹 ID
       */
      id?: number;
      /** @description 옵션 그룹 명칭 */
      name?: string;
      /** @description 그룹에 속한 옵션값 목록 */
      values?: components['schemas']['OptionValueResponse'][];
    };
    /** @description 그룹에 속한 옵션값 목록 */
    OptionValueResponse: {
      /**
       * Format: int64
       * @description 옵션값 ID
       */
      id?: number;
      /** @description 옵션값 명칭 */
      value?: string;
    };
    ProductDetailResponse: {
      /**
       * Format: int64
       * @description 상품 ID
       */
      id?: number;
      /** @description 브랜드명 */
      brandName?: string;
      /** @description 상품명 */
      productName?: string;
      /**
       * Format: int64
       * @description 정가
       */
      basePrice?: number;
      /**
       * Format: int32
       * @description 할인율(%)
       */
      discountRate?: number;
      /**
       * Format: int64
       * @description 최종 판매가
       */
      salePrice?: number;
      /**
       * Format: int64
       * @description 배송비
       */
      shippingFee?: number;
      /**
       * Format: date
       * @description 예상 발송 시작일
       */
      expectedShippingDate?: string;
      /** @description 환불 정책 */
      refundPolicy?: string;
      /** @description 상품 상세 설명 */
      description?: string;
      /** @description 상단 슬라이드 이미지 URL 리스트 */
      slideImageUrls?: string[];
      /** @description 하단 상세 설명 이미지 URL 리스트 */
      detailImageUrls?: string[];
      /** @description 옵션 그룹 목록 */
      optionGroups?: components['schemas']['OptionGroupResponse'][];
      /** @description 재고 및 옵션 조합 정보 (SKU) */
      skus?: components['schemas']['SkuResponse'][];
    };
    /** @description 재고 및 옵션 조합 정보 (SKU) */
    SkuResponse: {
      /**
       * Format: int64
       * @description SKU ID
       */
      id?: number;
      /**
       * Format: int64
       * @description 옵션 별 추가 금액
       */
      additionalPrice?: number;
      /**
       * Format: int32
       * @description 재고 수량
       */
      stockQuantity?: number;
      /** @description 매칭되는 옵션값 ID 리스트 (정렬된 순서) */
      optionValueIds?: number[];
    };
    CommonResponseSliceResponseOrderListResponse: {
      code?: string;
      message?: string;
      result?: components['schemas']['SliceResponseOrderListResponse'];
    };
    /** @description 주문 상품 목록 */
    OrderItemSummaryResponse: {
      /** @description 구매 당시 브랜드명 */
      brandName?: string;
      /** @description 구매 당시 상품명 */
      productName?: string;
      /** @description 구매 당시 옵션 정보 */
      optionDescription?: string;
      /** @description 구매 당시 상품 대표 이미지 url */
      productImageUrl?: string;
      /**
       * Format: int64
       * @description 판매가
       */
      salePrice?: number;
      /**
       * Format: int32
       * @description 구매 수량
       */
      quantity?: number;
    };
    /** @description 데이터 내용 */
    OrderListResponse: {
      /**
       * Format: int64
       * @description 주문 ID
       */
      id?: number;
      /**
       * Format: date-time
       * @description 주문 날짜
       */
      orderDate?: string;
      /** @description 주문 번호 */
      orderNumber?: string;
      /**
       * @description 주문 상태
       * @enum {string}
       */
      status?:
        | 'PENDING'
        | 'PAID'
        | 'PREPARING'
        | 'SHIPPING'
        | 'DELIVERED'
        | 'PURCHASE_CONFIRMED'
        | 'CANCELLED'
        | 'EXPIRED'
        | 'PENDING_REFUNDED'
        | 'REFUNDED';
      /** @description 주문 상품 목록 */
      items?: components['schemas']['OrderItemSummaryResponse'][];
    };
    SliceResponseOrderListResponse: {
      /** @description 데이터 내용 */
      content?: components['schemas']['OrderListResponse'][];
      /** @description 남은 페이지가 있는지 여부 (false면 마지막 페이지) */
      hasNext?: boolean;
      /**
       * Format: int64
       * @description 마지막 데이터의 ID, 다음 페이지 호출 시 해당 id를 cursorId에 넣어서 호출
       */
      lastId?: number;
    };
    CommonResponseOrderDetailResponse: {
      code?: string;
      message?: string;
      result?: components['schemas']['OrderDetailResponse'];
    };
    /** @description 배송지 정보 */
    OrderDetailDeliveryInfoResponse: {
      /** @description 수령인 이름 */
      recipientName?: string;
      /** @description 수령인 연락처 */
      phoneNumber?: string;
      /** @description 기본 주소 */
      baseAddress?: string;
      /** @description 상세 주소 */
      detailAddress?: string;
      /** @description 배송 요청사항 */
      shippingInstruction?: string;
    };
    OrderDetailResponse: {
      /**
       * Format: int64
       * @description 주문 ID
       */
      id?: number;
      /**
       * Format: date-time
       * @description 주문 날짜
       */
      orderDate?: string;
      /** @description 주문 번호 */
      orderNumber?: string;
      deliveryInfo?: components['schemas']['OrderDetailDeliveryInfoResponse'];
      shippingInfo?: components['schemas']['ShippingResponse'];
      /** @description 주문 상품 목록 */
      items?: components['schemas']['OrderItemResponse'][];
      summary?: components['schemas']['PaymentSummaryResponse'];
    };
    /** @description 주문 상품 목록 */
    OrderItemResponse: {
      /** @description 구매 당시 브랜드명 */
      brandName?: string;
      /** @description 구매 당시 상품명 */
      productName?: string;
      /** @description 구매 당시 옵션 정보 */
      optionDescription?: string;
      /** @description 구매 당시 상품 대표 이미지 url */
      productImageUrl?: string;
      /**
       * Format: int64
       * @description 총 판매가
       */
      totalSalePrice?: number;
      /**
       * Format: int32
       * @description 구매 수량
       */
      quantity?: number;
    };
    /** @description 결제 금액 요약 */
    PaymentSummaryResponse: {
      /**
       * Format: int64
       * @description 총 상품금액 (할인 전 합계)
       */
      totalProductPrice?: number;
      /**
       * Format: int64
       * @description 아지트 멤버십 할인 금액
       */
      membershipDiscount?: number;
      /**
       * Format: int64
       * @description 포인트 할인 금액
       */
      pointDiscount?: number;
      /**
       * Format: int64
       * @description 배송비
       */
      shippingFee?: number;
      /**
       * Format: int64
       * @description 최종 결제 예정 금액
       */
      totalPaymentPrice?: number;
    };
    /** @description 배송 정보 */
    ShippingResponse: {
      /** @description 택배사 (배송 전일 경우 null) */
      courier?: string;
      /** @description 운송장 번호 (배송 전일 경우 null) */
      trackingNumber?: string;
    };
    /** @description 주문할 상품 목록 */
    CheckoutItemResponse: {
      /** @description 브랜드명 */
      brandName?: string;
      /** @description 상품명 */
      productName?: string;
      /** @description 선택 옵션 정보 */
      optionDescription?: string;
      /** @description 상품 대표 이미지 URL */
      productImageUrl?: string;
      /**
       * Format: int64
       * @description 상품 정가
       */
      basePrice?: number;
      /**
       * Format: int64
       * @description 상품 판매가
       */
      salePrice?: number;
      /**
       * Format: int32
       * @description 장바구니에 담은 수량
       */
      quantity?: number;
      /**
       * Format: int64
       * @description 총 정가
       */
      totalBasePrice?: number;
      /**
       * Format: int64
       * @description 총 판매가
       */
      totalSalePrice?: number;
    };
    CommonResponseOrderCheckoutResponse: {
      code?: string;
      message?: string;
      result?: components['schemas']['OrderCheckoutResponse'];
    };
    /** @description 배송지 정보 (기본 배송지 우선, 없으면 null) */
    DeliveryAddressResponse: {
      /**
       * Format: int64
       * @description 배송지 ID
       */
      id?: number;
      /** @description 수령인 이름 */
      recipientName?: string;
      /** @description 수령인 연락처 */
      phoneNumber?: string;
      /** @description 우편번호 */
      zipcode?: string;
      /** @description 기본 주소 */
      baseAddress?: string;
      /** @description 상세 주소 */
      detailAddress?: string;
      /** @description 기본 배송지 여부 */
      isDefault?: boolean;
    };
    OrderCheckoutResponse: {
      deliveryInfo?: components['schemas']['DeliveryAddressResponse'];
      /** @description 주문할 상품 목록 */
      items?: components['schemas']['CheckoutItemResponse'][];
      pointInfo?: components['schemas']['PointInfoResponse'];
      /** @description 사용 가능한 결제 수단 목록 */
      paymentMethods?: components['schemas']['PaymentMethodResponse'][];
      summary?: components['schemas']['CheckoutSummaryResponse'];
    };
    /** @description 사용 가능한 결제 수단 목록 */
    PaymentMethodResponse: {
      /** @description 결제 수단 코드 */
      code?: string;
      /** @description 결제 수단 설명 */
      description?: string;
      /** @description 활성화 여부 */
      isEnabled?: boolean;
    };
    /** @description 포인트 정보 */
    PointInfoResponse: {
      /**
       * Format: int64
       * @description 보유 포인트
       */
      availablePoints?: number;
      /**
       * Format: int64
       * @description 최소 사용 가능 포인트
       */
      minUsePoints?: number;
      /**
       * Format: int64
       * @description 포인트 사용 단위
       */
      pointUnit?: number;
    };
    CommonResponseMyInfoResponse: {
      code?: string;
      message?: string;
      result?: components['schemas']['MyInfoResponse'];
    };
    MyInfoResponse: {
      /**
       * Format: int64
       * @description 사용자 ID
       */
      id?: number;
      /** @description 닉네임 */
      nickname?: string;
      /**
       * Format: int64
       * @description 크루 ID
       */
      crewId?: number;
      /**
       * @description 크루 내 역할
       * @enum {string}
       */
      crewMemberRole?: 'LEADER' | 'MEMBER';
      /** @description 프로필 이미지 URL */
      profileImageUrl?: string;
      /**
       * Format: int32
       * @description 누적 출석 횟수
       */
      totalAttendanceCount?: number;
      /**
       * Format: int64
       * @description 포인트
       */
      totalPoints?: number;
    };
    CommonResponseCrewMemberListResponse: {
      code?: string;
      message?: string;
      result?: components['schemas']['CrewMemberListResponse'];
    };
    /** @description 멤버 목록 */
    CrewMemberDetailResponse: {
      /**
       * Format: int64
       * @description 멤버 ID
       */
      id?: number;
      /** @description 닉네임 */
      nickname?: string;
      /** @description 프로필 이미지 URL */
      profileImageUrl?: string;
      /**
       * @description 크루 내 역할
       * @enum {string}
       */
      role?: 'LEADER' | 'MEMBER';
      /**
       * Format: date-time
       * @description 가입일
       */
      joinedDate?: string;
    };
    CrewMemberListResponse: {
      /**
       * Format: int64
       * @description 전체 멤버 수
       */
      totalCount?: number;
      /** @description 멤버 목록 */
      content?: components['schemas']['CrewMemberDetailResponse'][];
      /** @description 남은 페이지가 있는지 여부 (false면 마지막 페이지) */
      hasNext?: boolean;
      /**
       * Format: int64
       * @description 마지막 데이터의 ID, 다음 페이지 호출 시 해당 id를 cursorId에 넣어서 호출
       */
      lastId?: number;
    };
    CommonResponseCrewJoinStatusResponse: {
      code?: string;
      message?: string;
      result?: components['schemas']['CrewJoinStatusResponse'];
    };
    CrewJoinStatusResponse: {
      /**
       * Format: int64
       * @description 크루 ID
       */
      crewId?: number;
      /** @description 크루 이름 */
      name?: string;
      /**
       * @description 멤버 상태
       * @enum {string}
       */
      status?: 'REQUESTED' | 'JOINED' | 'REJECTED' | 'EXITED';
    };
    CommonResponseListJoinRequestMemberResponse: {
      code?: string;
      message?: string;
      result?: components['schemas']['JoinRequestMemberResponse'][];
    };
    JoinRequestMemberResponse: {
      /**
       * Format: int64
       * @description 멤버 ID
       */
      memberId?: number;
      /** @description 닉네임 */
      nickname?: string;
      /** @description 프로필 이미지 URL */
      profileImageUrl?: string;
      /**
       * Format: date-time
       * @description 가입 신청 일시
       */
      requestedAt?: string;
    };
    CommonResponseCrewInvitationResponse: {
      code?: string;
      message?: string;
      result?: components['schemas']['CrewInvitationResponse'];
    };
    CrewInvitationResponse: {
      /**
       * Format: int64
       * @description 크루 ID
       */
      crewId?: number;
      /** @description 크루 이름 */
      name?: string;
      /** @description 크루 카테고리 */
      category?: string;
      /**
       * Format: int64
       * @description 크루에 가입되어 있는 멤버 수
       */
      memberCount?: number;
    };
    /** @description 장바구니 상품 목록 */
    CartItemDetail: {
      /**
       * Format: int64
       * @description 장바구니 항목 ID
       */
      id?: number;
      /** @description 브랜드명 */
      brandName?: string;
      /** @description 상품명 */
      productName?: string;
      /**
       * Format: date
       * @description 예상 발송 시작일
       */
      expectedShippingDate?: string;
      /**
       * Format: int64
       * @description 상품 sku ID
       */
      productSkuId?: number;
      /** @description 선택 옵션 정보 */
      optionDescription?: string;
      /** @description 상품 대표 이미지 URL */
      productImageUrl?: string;
      /**
       * Format: int64
       * @description 상품 정가
       */
      basePrice?: number;
      /**
       * Format: int64
       * @description 상품 판매가
       */
      salePrice?: number;
      /**
       * Format: int32
       * @description 장바구니에 담은 수량
       */
      quantity?: number;
      /** @description 품절 여부 */
      isOutOfStock?: boolean;
    };
    CartListResponse: {
      /** @description 장바구니 상품 목록 */
      items?: components['schemas']['CartItemDetail'][];
      /**
       * Format: int64
       * @description 총 상품금액 (할인 전 합계)
       */
      totalProductPrice?: number;
      /**
       * Format: int64
       * @description 아지트 멤버십 할인 금액
       */
      membershipDiscount?: number;
      /**
       * Format: int64
       * @description 배송비
       */
      shippingFee?: number;
      /**
       * Format: int64
       * @description 최종 결제 예정 금액
       */
      totalPaymentPrice?: number;
    };
    CommonResponseCartListResponse: {
      code?: string;
      message?: string;
      result?: components['schemas']['CartListResponse'];
    };
    CartItemCountResponse: {
      /**
       * Format: int64
       * @description 장바구니 아이템 종류 수
       */
      count?: number;
    };
    CommonResponseCartItemCountResponse: {
      code?: string;
      message?: string;
      result?: components['schemas']['CartItemCountResponse'];
    };
    CommonResponseListDeliveryAddressResponse: {
      code?: string;
      message?: string;
      result?: components['schemas']['DeliveryAddressResponse'][];
    };
    CartItemDeleteRequest: {
      /** @description 삭제할 장바구니 ID 리스트 */
      cartItemIds: number[];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  updateDeliveryAddress: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        addressId: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateDeliveryAddressRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['CommonResponseVoid'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  deleteDeliveryAddress: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        addressId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['CommonResponseVoid'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  getOrders: {
    parameters: {
      query: {
        query: components['schemas']['CursorPageQuery'];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['CommonResponseSliceResponseOrderListResponse'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  createOrder: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateOrderRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['CommonResponseCreateOrderResponse'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  agreeToTerms: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AgreeToTermsRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['CommonResponseVoid'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  withdraw: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['CommonResponseVoid'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  confirmMemberStatus: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['CommonResponseVoid'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  createCrew: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateCrewRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['CommonResponseCreateCrewResponse'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  rejectJoinRequest: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        crewId: number;
        targetMemberId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['CommonResponseVoid'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  approveJoinRequest: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        crewId: number;
        targetMemberId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['CommonResponseVoid'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  joinCrew: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['JoinCrewRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['CommonResponseVoid'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  addCartItem: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AddToCartRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['CommonResponseVoid'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  deleteItems: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CartItemDeleteRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['CommonResponseVoid'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  socialLogin: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        provider: 'KAKAO' | 'APPLE';
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SocialLoginRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['CommonResponseSocialLoginResponse'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  appleLogin: {
    parameters: {
      query: {
        code: string;
        id_token: string;
        user?: string;
        state?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  reissue: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['CommonResponseSocialLoginResponse'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['CommonResponseVoid'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  receiveAppleNotification: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AppleNotificationRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['CommonResponseVoid'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  getDeliveryAddresses: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['CommonResponseListDeliveryAddressResponse'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  registerDeliveryAddress: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RegisterDeliveryAddressRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['CommonResponseVoid'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  cancelOrder: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        orderNumber: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['CommonResponseVoid'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  getProducts: {
    parameters: {
      query: {
        query: components['schemas']['CursorPageQuery'];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['CommonResponseSliceResponseProductListResponse'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  getProduct: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description 조회할 상품 ID */
        productId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['CommonResponseProductDetailResponse'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  getOrderDetail: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        orderNumber: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['CommonResponseOrderDetailResponse'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  getCheckoutInfoDirect: {
    parameters: {
      query: {
        skuId: number;
        quantity: number;
        deliveryAddressId?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['CommonResponseOrderCheckoutResponse'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  getCheckoutInfoFromCart: {
    parameters: {
      query: {
        cartItemIds: number[];
        deliveryAddressId?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['CommonResponseOrderCheckoutResponse'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  getMyInfo: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['CommonResponseMyInfoResponse'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  getCrewMembers: {
    parameters: {
      query: {
        query: components['schemas']['CursorPageQuery'];
      };
      header?: never;
      path: {
        crewId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['CommonResponseCrewMemberListResponse'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  getCrewJoinStatus: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        crewId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['CommonResponseCrewJoinStatusResponse'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  getJoinRequests: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        crewId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['CommonResponseListJoinRequestMemberResponse'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  getCrewByInvitation: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        invitationCode: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['CommonResponseCrewInvitationResponse'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  getCarts: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['CommonResponseCartListResponse'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  getCartItemCount: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['CommonResponseCartItemCountResponse'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
}
