export const REGION = {
  SEOUL: 'SEOUL',
  GYEONGGI_INCHEON: 'GYEONGGI_INCHEON',
  CHUNGCHEONG_DAEJEON: 'CHUNGCHEONG_DAEJEON',
  JEOLLA_GWANGJU: 'JEOLLA_GWANGJU',
  GYEONGBUK_DAEGU: 'GYEONGBUK_DAEGU',
  GYEONGNAM_BUSAN: 'GYEONGNAM_BUSAN',
  GANGWON: 'GANGWON',
  JEJU: 'JEJU',
} as const;

export type RegionType = (typeof REGION)[keyof typeof REGION];
